[project]
name = "aichemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Malcolm", email = "malcolm.krolick@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
aichemy = "aichemy:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
